# Site
name: "Onshape4FRC"
title: "Onshape4FRC"
description: "Onshape CAD and Design resources to help teach for FRC."
logo: "assets/images/onshape4frc-logo.png"
favicon: "assets/images/logo.png"
baseurl: ""
google_analytics: "UA-170618487-1"
disqus: "demowebsite"
# mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  max:
    name: Max Westwater
    display_name: Max Westwater
    team: 6328/5254
    avatar: https://www.chiefdelphi.com/user_avatar/www.chiefdelphi.com/maximillian/120/146348_2.png
    email: maxwestwater@gmail.com
    cd: maximillian
    description: "The lead silver medalist."
  jack:
    name: Jack Tervay
    display_name: Jack Tervay
    team: 6328/2791
    avatar: https://www.chiefdelphi.com/letter_avatar_proxy/v4/letter/j/5daacb/120.png
    email: jacktervay@gmail.com
    cd: jacktervay
    description: "6328 lead technical mentor."

# Featurescripts
featurescripts:
  TubeConverter:
    name: Tube Converter
    link: https://cad.onshape.com/documents/95c00401c440b44ad8799ef5/w/1f1ebce01a3b8eb6fa102975/e/b92d638809ae48771ecc7ad8
    image: /assets/images/tubeconverter.png
    description: Coverts a raw extrusion into a tube like is typically used in FRC with parameters for tube thickness and hole patterns.
  FilletXpert:
    name: FilletXpert
    link: https://cad.onshape.com/documents/95c00401c440b44ad8799ef5/w/1f1ebce01a3b8eb6fa102975/e/b92d638809ae48771ecc7ad8
    image: /assets/images/FilletXpert.png
    description: Fillet all edges touching a face in a certain direction. Based on Solidworksâ€™ FilletXpert feature.
  shaft:
    name: Shaft Generator
    link: https://cad.onshape.com/documents/95c00401c440b44ad8799ef5/w/1f1ebce01a3b8eb6fa102975/e/b92d638809ae48771ecc7ad8
    image: /assets/images/shaft-generator.png
    description: Quickly generate shafts with parameters for choosing shaft retention methods.
  spacer:
    name: Spacer Generator
    link: https://cad.onshape.com/documents/95c00401c440b44ad8799ef5/w/1f1ebce01a3b8eb6fa102975/e/b92d638809ae48771ecc7ad8
    image: /assets/images/spacer-generator.png
    description: Quickly generate custom spacers.
  gusset:
    name: Gusset Generator
    link: https://cad.onshape.com/documents/95c00401c440b44ad8799ef5/w/1f1ebce01a3b8eb6fa102975/e/b92d638809ae48771ecc7ad8
    image: https://www.chiefdelphi.com/uploads/default/original/3X/8/f/8f7ba06976668b45d5ab61a55deec51f812a1ab0.png
    description: Generate gussets by simply selecting the holes which define the shape of the gusset.
  iso:
    name: Isogrid Pattern
    link: https://cad.onshape.com/documents/95c00401c440b44ad8799ef5/w/1f1ebce01a3b8eb6fa102975/e/b92d638809ae48771ecc7ad8
    image: /assets/images/isogrid.png
    description: Adds an Isogrid pattern to parts.
  lighten:
    name: Lighten
    link: https://cad.onshape.com/documents/573f7d70e4b0fddafb52148c/v/85bb63ae5685ae3614116952/e/5eccf6d369b0312a728d77d3
    image: /assets/images/lighten.png
    description: Lighten your parts easier with this featurescript and a sketch of the areas you want removed.
  # Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: blog/page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, vendor]

host: 0.0.0.0
